### ISSUE TITLE
Provide `repo` input

### ISSUE THREAD

**Issue by rnoxy** [iterative/gto-action#18]
Please add an input `repo` to behave like the `--repo` option in CLI.

**Comment by aguschin** [comment]
Related to https://github.com/iterative/gto/issues/364#issuecomment-1567023219

**Comment by aguschin** [comment]
Hi @rnoxy! This action should be used in GH actions https://docs.github.com/en/actions (read CI/CD for GitHub) triggered by GTO tags (version registration or stage assignment) for the repo in question, so I'm not quite sure what is the meaning of working with a remote repo here. Could you please explain your use case? Thanks!

**Comment by aguschin** [comment]
closing this @rnoxy, feel free to reopen if you have any questions!
