### ISSUE TITLE
GTO version differs from release in GTO repository

### ISSUE THREAD

**Issue by SebaMontoya** [iterative/gto-action#20]
Hi I was trying to use GTO in github actions and I am getting the following error when the workflow runs

`pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.0.3/migration/#basesettings-has-moved-to-pydantic-settings for more details.`

The version of pydantic is pinned in gto version 0.3.5 which should solve the problem, please let me know if a pull request is needed for this change.

Thanks!

**Comment by shcheklein** [comment]
@SebaMontoya I've bumped the dependencies. Could you please give it a try again and confirm?
